config/routes.rb
Proj::Application.routes.draw do
  resources :plants

  get "home/index"

  

 root :to => "home#index"

end

app/models/plant.rb
class Plant < ActiveRecord::Base
  validates :plant_type, :presence =>true
  validates :x, :presence =>true
  validates :y, :presence =>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @params=params[:id]
    @x=params[:x]
    @y=params[:y]
    @plant_type=params[:plant_type]
  
    @plant = Plant.find(:all)
  
    if @params == "make_turn"
      @plant.each do |plant|
        plant.process_end=plant.process_end-10000000
        if plant.process_end < 0 
          plant.process_end = 0
        end
        plant.save
      end
    end

    @already=false
  
    if @params=="seed"
      @plant.each do |plant|
        if @x.to_s==plant.x.to_s
          if @y.to_s==plant.x.to_s
            @already=true
          end
        end
      end 
      if @already==false
        seed=Plant.new
        seed.plant_type=@plant_type
        seed.x=@x
        seed.y=@y
        seed.process_end=49000000
        seed.save
      end
    end

    if @params=="grab"
      @plant.each do |plant|
        if @x.to_s==plant.x.to_s
          if @y.to_s==plant.y.to_s
            if plant.process_end<10000000
              plant.destroy
            end
          end
        end
      end
    end

    @plant = Plant.find(:all)

  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  # GET /plants
  # GET /plants.xml
  def index
    @plants = Plant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @plants }
    end
  end

  # GET /plants/1
  # GET /plants/1.xml
  def show
    @plant = Plant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render xml: @plant }
    end
  end



  # GET /plants/1/edit
  def edit
    @plant = Plant.find(params[:id])
  end

  # POST /plants
  # POST /plants.xml
  def create
    @plant = Plant.new(params[:plant])

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.xml { render xml: @plant, status: :created, location: @plant }
      else
        format.html { render action: "new" }
        format.xml { render xml: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plants/1
  # PUT /plants/1.xml
  def update
    @plant = Plant.find(params[:id])

    respond_to do |format|
      if @plant.update_attributes(params[:plant])
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.xml { head :ok }
      else
        format.html { render action: "edit" }
        format.xml { render xml: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.xml
  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to plants_url }
      format.xml { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/home/index.html.erb
<country>
<field zero_x="0" zero_y="0" size_x="10" size_y="10">


<% for pl in @plant -%><<%=pl.plant_type %> id="<%=pl.id%>" x="<%=pl.x%>" y="<%=pl.y%>" process_end="<%=pl.process_end%>"/>
<%  end %>

</field>
</country>
<%=@answer%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proj</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plant_type %><br />
    <%= f.text_field :plant_type %>
  </div>
  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.number_field :y %>
  </div>
  <div class="field">
    <%= f.label :process_end %><br />
    <%= f.number_field :process_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<h1>Listing plants</h1>

<table>
  <tr>
    <th>Plant type</th>
    <th>Id</th>
    <th>X</th>
    <th>Y</th>
    <th>Process end</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plants.each do |plant| %>
  <tr>
    <td><%= plant.plant_type %></td>
    <td><%= plant.id %></td>
    <td><%= plant.x %></td>
    <td><%= plant.y %></td>
    <td><%= plant.process_end %></td>
    <td><%= link_to 'Show', plant %></td>
    <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
    <td><%= link_to 'Destroy', plant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Plant type:</b>
  <%= @plant.plant_type %>
</p>

<p>
  <b>Id:</b>
  <%= @plant.id %>
</p>

<p>
  <b>X:</b>
  <%= @plant.x %>
</p>

<p>
  <b>Y:</b>
  <%= @plant.y %>
</p>

<p>
  <b>Process end:</b>
  <%= @plant.process_end %>
</p>


<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>